### ISSUE TITLE
Runing

### ISSUE THREAD

**Issue by ZZcat** [kyoung/trek#11]
How do we view this program in the web browser???
When I run it with npm start after npm install and npm test it gives me

Trek@0.1.19 start C:\Users\zach\Desktop\trek
coffee ./trek/Server.coffee
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Message from Enterprise [alert]:
yellow
Connecting socket messaging...
Stardate 8624.05
Ships in game...
Enterprise 77794
AI Ships <>

**Comment by ZZcat** [comment]
When I run it with npm start after npm install and npm test it gives me 

> Trek@0.1.19 start C:\Users\zach\Desktop\trek
> coffee ./trek/Server.coffee

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Message from Enterprise [alert]:
yellow
Connecting socket messaging...
Stardate 8624.05
Ships in game...
Enterprise 77794
AI Ships <<DEBUG>>

**Comment by kyoung** [comment]
Hey @ZZcat; sorry for the long delay; I really wasn't watching the Issues.

I'll get around to making a more user friendly output, but for now, you should be able to browse to your local host at port 8080.

In order to log into a ship, you'll need it's prefix code (that's those number listed after the "ships in game" message). The idea being that when you start a game, you can hand out those codes to the different teams if they're in different rooms.
